version: "3.9"
services:
  web:
    build:
      context: web
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build:
      context: api
      dockerfile: refs/Dockerfile.4
    ports:
      - "8081:8081"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
