FROM ubuntu
WORKDIR /app
RUN apt update && \
  apt install -y curl && \
  curl -OJL https://go.dev/dl/go1.19.3.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz && \
  rm go1.19.3.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN go build -o /fruits
ENTRYPOINT ["/fruits"]
