FROM golang:1.19.3-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /fruits

FROM gcr.io/distroless/static-debian11 AS runner
COPY --from=builder /fruits /fruits
ENTRYPOINT ["/fruits"]
