GET http://localhost:8081/sell?fruit=apple&quantity=5
###
GET http://localhost:8081/
###
GET http://localhost:8081/buy?fruit=apple&quantity=10
###
POST http://localhost:8081/buy
Content-Type: application/json

{
  "fruit": "orange",
  "quantity": 10
}
###
GET http://localhost:8081/buy?fruit=orange&quantity=20
###
GET http://localhost:8081
###
GET http://localhost:8081/sell?fruit=apple&quantity=5
###
POST http://localhost:8081/sell
Content-Type: application/json

{
  "fruit": "orange",
  "quantity": 10
}
###
GET http://localhost:8081/sell?fruit=orange&quantity=10
###
GET http://localhost:8081
